#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$bootstrapper = new Mihaeu\MyDiary\Bootstrapper();
$bootstrapper->createBookConfig();

$easybookScript = file_get_contents(__DIR__.'/vendor/easybook/easybook/book');
$easybookScript = str_replace('<?php', '', $easybookScript);
eval($easybookScript);